IUBAT_E_Learning_Platform/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views, user_login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('404', views.page_not_found, name='404'),
    path('base', views.base, name='base'),
    path('', views.home, name='home'),
    path('info', views.info, name='info'),
    path('courses', views.courses, name='courses'),
    path('courses/filter-data', views.filter_data, name="filter-data"),
    path('search', views.search_course, name='search_course'),
    path('course/<slug:slug>', views.course_details, name="course_details"),
    path('checkout/<slug:slug>', views.checkout, name='checkout'),
    path('my-course', views.my_course, name='my_course'),
    path('verify-payment/<slug:slug>/<int:pin>/<int:pk>', views.verify_payment, name='verify_payment'),
    path('verify-payment/success/<slug:slug>/<int:pk>', views.success, name='success'),
    path('verify-payment/failed', views.failed, name='failed'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', user_login.register, name='register'),
    path('doLogin', user_login.doLogin, name='doLogin'),
    path('accounts/profile', user_login.profile, name='profile'),
    path('accounts/profile/update', user_login.profile_update, name='profile_update'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.urls import reverse

# Create your models here.


class Categories(models.Model):
    icon = models.ImageField(upload_to="Media/featured_img", null=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def get_all_category(self):
        return Categories.objects.all().order_by('id')


class Level(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Language(models.Model):
    language = models.CharField(max_length=100)

    def __str__(self):
        return self.language


class Instructor(models.Model):
    instructor_profile = models.ImageField(upload_to="Media/instructor")
    name = models.CharField(max_length=100, null=True)
    instructor_title = models.CharField(max_length=100, null=True)
    about_instructor = models.TextField()

    def __str__(self):
        return self.name


class Course(models.Model):
    STATUS = (
        ('PUBLISH', 'PUBLISH'),
        ('DRAFT', 'DRAFT'),
    )

    featured_image = models.ImageField(upload_to="Media/featured_img", null=True)
    featured_video = models.CharField(max_length=300, null=True)
    title = models.CharField(max_length=500)
    created_at = models.DateField(auto_now_add=True)
    instructor = models.ForeignKey(Instructor, on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    level = models.ForeignKey(Level, on_delete=models.CASCADE, null=True)
    description = models.TextField()
    semi_des = models.CharField(max_length=500, null=True)
    price = models.IntegerField(null=True, default=0)
    discount = models.IntegerField(null=True)
    language = models.ForeignKey(Language, on_delete=models.CASCADE, null=True)
    deadline = models.CharField(max_length=100, null=True)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    status = models.CharField(choices=STATUS, max_length=100, null=True)
    certificate = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("course_details", kwargs={'slug': self.slug})


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Course.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, Course)


class What_you_learn(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    points = models.CharField(max_length=500)

    def __str__(self):
        return self.points


class Requirements(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    points = models.CharField(max_length=500)

    def __str__(self):
        return self.points


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name + " - " + self.course.title


class Video(models.Model):
    serial_number = models.IntegerField(null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    youtube_id = models.CharField(max_length=200)
    time_duration = models.IntegerField(null=True)
    preview = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class UserCourse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    paid = models.BooleanField(default=0)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username + " buys " + self.course.title + " course"


class Payment(models.Model):
    order_id = models.CharField(max_length=100, null=True, blank=True)
    payment_id = models.CharField(max_length=100, null=True, blank=True)
    user_course = models.ForeignKey(UserCourse, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=20, null=True, blank=True)
    university_name = models.CharField(max_length=100, null=True, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    address_1 = models.CharField(max_length=150, null=True, blank=True)
    address_2 = models.CharField(max_length=150, null=True, blank=True)
    postcode = models.CharField(max_length=4, null=True, blank=True)
    phone = models.CharField(max_length=11, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.user.first_name + " -- " + self.course.title


class Review(models.Model):
    name = models.CharField(max_length=100, null=True)
    course_name = models.CharField(max_length=200, null=True)
    review_course = models.TextField(max_length=1000, null=True)

    def __str__(self):
        return "Reviews of " + self.course_name

templates/main/courses.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load course_tags %}


<!-- Ajax-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
$(document).ready(function(){

	$(".filter-checkbox").on('click', function(){
		var filter_object={};
		$(".filter-checkbox").each(function(index,ele){
			var filter_value=$(this).val();
			var filter_key=$(this).data('filter');
		    console.log(filter_key,filter_value);
			filter_object[filter_key]=Array.from(document.querySelectorAll('input[data-filter='+filter_key+']:checked')).map(function(el){
			 	return el.value;
			});
		});

		$.ajax({
			url:'{% url 'filter-data' %}',
			data:filter_object,
			dataType:'json',
			success:function(res){
			    console.log(res)
				$("#filteredCourses").html(res.data);
				var filter_value=$(this).val();
			    var filter_key=$(this).data('filter');
			}
		});
	});
});
</script>

<section class="filter-courses mb-5">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-6 mb-5">
            <div class="login-title text-center mt-5">
              <h2>Courses</h2>
              <!-- <div class="login-nav"> -->
              <!-- breadcrumb -->
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item">
                    <a href="{%url 'home'%}">Home</a>
                  </li>
                  <li class="breadcrumb-item active" aria-current="page">
                    Courses
                  </li>
                </ol>
              </nav>
              <!-- breadcrumb -->
              <!-- </div> -->
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4 col-md-12 mb-4">
            <div class="filtered">
              <div id="coursefilter1">
                <div class="filter-category">
                  <h4
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#coursefiltercollapse1"
                    aria-expanded="true"
                    aria-controls="coursefiltercollapse1"
                  >
                    Category <i class="fa-solid fa-plus"></i>
                  </h4>
                </div>
              </div>
              <div
                id="coursefiltercollapse1"
                class="collapse show mt-n2 px-6 pb-6"
                aria-labelledby="coursefilter1"
                data-parent="#courseSidebar"
              >
                <ul class="list-group list-unstyled list-group list-checkbox">
                    {% for type in category %}
                  <li class="custom-control custom-checkbox">
                    <input
                      type="checkbox"
                      class="form-check-input me-1 custom-control-input filter-checkbox"
                      id="category-{{type.id}}"
                      data-filter="category"
                      value="{{type.id}}"
                    />
                    <label
                      class="custom-control-label font-size-base"
                      for="category-{{type.id}}"
                      >{{type.name}} ({{type.course_set.all.count}})</label
                    >
                  </li>
                    {% endfor %}
                </ul>
                </div>

              <div id="coursefilter2">
                <div class="filter-category mt-5">
                  <h4
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#coursefiltercollapse2"
                    aria-expanded="true"
                    aria-controls="coursefiltercollapse2"
                  >
                    Price <i class="fa-solid fa-plus"></i>
                  </h4>
                </div>
              </div>
              <div
                id="coursefiltercollapse2"
                class="collapse show mt-n2 px-6 pb-6"
                aria-labelledby="coursefilter2"
                data-parent="#courseSidebar"
              >
                <ul class="list-group list-unstyled list-group list-checkbox">

                  <li class="custom-control custom-checkbox custom-radio">
                    <input
                      type="checkbox"
                      class="form-check-input me-1 custom-control-input filter-checkbox"
                      id="price-1"
                      name="customRadio"
                      value="PriceAll" data-filter="price"
                    />
                    <label
                      class="custom-control-label font-size-base"
                      for="price-1"
                      >All ({{course.all.count}})</label>
                  </li>

                  <li class="custom-control custom-checkbox custom-radio">
                    <input
                      type="checkbox"
                      class="form-check-input me-1 custom-control-input filter-checkbox"
                      id="price-2"
                      name="customRadio"
                      value="PriceFree" data-filter="price"
                    />
                    <label
                      class="custom-control-label font-size-base"
                      for="price-2"
                      >Free ({{freeCourse_count}})</label>
                  </li>

                  <li class="custom-control custom-checkbox custom-radio">
                    <input
                      type="checkbox"
                      class="form-check-input me-1 custom-control-input filter-checkbox"
                      id="price-3"
                      name="customRadio"
                      value="PricePaid" data-filter="price"
                    />
                    <label
                      class="custom-control-label font-size-base"
                      for="price-3"
                      >Paid ({{paidCourse_count}})</label>
                  </li>

                </ul>
                </div>

              <div id="coursefilter3">
                <div class="filter-category mt-5">
                  <h4
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#coursefiltercollapse3"
                    aria-expanded="true"
                    aria-controls="coursefiltercollapse3"
                  >
                    Level <i class="fa-solid fa-plus"></i>
                  </h4>
                </div>
              </div>
              <div
                id="coursefiltercollapse3"
                class="collapse show mt-n2 px-6 pb-6"
                aria-labelledby="coursefilter3"
                data-parent="#courseSidebar"
              >
                <ul class="list-group list-unstyled list-group list-checkbox">
                    {% for type in level %}
                  <li class="custom-control custom-checkbox">
                    <input
                      type="checkbox"
                      class="form-check-input me-1 custom-control-input filter-checkbox"
                      id="level-{{type.id}}"
                      data-filter="level"
                      value="{{type.id}}"
                    />
                    <label
                      class="custom-control-label font-size-base"
                      for="level-{{type.id}}"
                      >{{type.name}} ({{type.course_set.all.count}})</label>
                  </li>
                    {% endfor %}
                </ul>
                </div>
            </div>
          </div>
          <div class="col-lg-8 col-md-12">
            <div class="row" id="filteredCourses">
              {% for single_course in course %}
              <div class="col-md-6">
                <div class="card">
                  <div class="course-img-container">
                    <img
                      src="{{single_course.featured_image}}"
                      class="card-img-top img-fluid"
                      alt=""
                    />
                  </div>
                  <div class="card-body">
                    <div class="course-info">
                      <span style="color: #7783ac">Topic: {{single_course.category.name}}</span>
                      {% if user.is_authenticated %}
                      <a style="text-decoration:none; color:black" href="{{ single_course.get_absolute_url }}"><h5 class="card-title">{{single_course.title}}</h5></a>
                      {% else %}
                      <a style="text-decoration:none; color:black" href="/accounts/login/"><h5 class="card-title">{{single_course.title}}</h5></a>
                      {% endif %}
                      <h6>Instructor: <i>{{single_course.instructor.name}}</i></h6>
                      <p class="card-text">
                        {{single_course.semi_des}}
                      </p>
                      <div class="course-info">
                        <div class="float-start">
                          <span style="color: #7783ac"
                            ><i class="fa-solid fa-users"></i> {{single_course.usercourse_set.all.count}} students</span>
                          <br />
                          <span style="color: #7783ac"
                            ><i class="fa-solid fa-book"></i> {{single_course.video_set.all.count}} lessons</span>
                        </div>

                        <div class="float-end">
                          {% if single_course.price == 0 %}
                            <h6 style="color: rgb(1, 130, 10); font-weight: 900">
                              <span class="badge bg-success" style="font-size: 18px">Free</span>
                            </h6>
                          {% else %}
                            <del style="color: red; font-weight: 900">৳ {{single_course.price}}</del>
                            <h6 style="color: rgb(1, 130, 10); font-weight: 900">
                                ৳ {% discount_calculation single_course.price single_course.discount %}
                            </h6>
                          {% endif %}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

templates/main/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load course_tags %}

    <!-- hero -->
    <section class="hero mb-5">
      <div class="hero-overlay">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <div class="hero-content mt-5 mb-5">
                <h2>Learn online from the faculties in virtual education</h2>
                <p class="mt-5 mb-5">
                  Expand your own skills and engage with a global network of
                  learners through our flexible, online courses. Wherever you
                  are in your career—or the world—IUBAT E-Learning Platform can
                  help you achieve your goals for your future professinal life.
                </p>
                <a href="#featured-courses" class="mt-3 btn btn-light"
                  ><h4>Explore All Courses</h4></a
                >
              </div>
            </div>
            <div class="col-md-6 d-flex flex-wrap align-content-center">
              <iframe
                width="560"
                height="315"
                src="https://www.youtube.com/embed/1jmsVl9Eges"
                title="YouTube video player"
                frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen
              ></iframe>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- hero -->

    <!-- subject-area -->
    <section class="subject-area mb-5">
      <div class="container">
        <div class="row">
          <div class="subject-area-title mb-2">
            <h4>Choose a subject area:</h4>
          </div>
        </div>
        <div class="row justify-content-center">
          <div class="col-md-4">
            <div class="single-subject">
              <h5>Computer Science & Engineering</h5>
            </div>
          </div>
          <div class="col-md-4">
            <div class="single-subject">
              <h5>Electrical & Electronics Engineering</h5>
            </div>
          </div>
          <div class="col-md-4">
            <div class="single-subject">
              <h5>Mechanical Engineering</h5>
            </div>
          </div>
          <div class="col-md-4">
            <div class="single-subject">
              <h5>Civil Engineering</h5>
            </div>
          </div>
          <div class="col-md-4">
            <div class="single-subject">
              <h5>Finance & Accounting</h5>
            </div>
          </div>
          <div class="col-md-4">
            <div class="single-subject">
              <h5>Agricultural Science</h5>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- subject-area -->

    <!-- featured-courses  -->
    <section class="featured-courses" id="featured-courses">
      <div class="container">
        <div class="row">
          <h4 style="font-weight: 900" class="text-center mt-3 mb-4">
            ----- FEATURED COURSES -----
          </h4>
        </div>
        <div class="row mb-5 justify-content-center">
          {% for single_course in course %}
          <div class="col-lg-4 col-md-6">
            <div class="card">
              <div class="course-img-container">
                <img
                  src="{{single_course.featured_image}}"
                  class="card-img-top img-fluid"
                  alt=""
                />
              </div>
              <div class="card-body">
                <div class="course-info">
                  <span style="color: #7783ac">Topic: {{single_course.category.name}}</span>
                  {% if user.is_authenticated %}
                  <a style="text-decoration:none; color:black" href="{{ single_course.get_absolute_url }}"><h5 class="card-title">{{single_course.title}}</h5></a>
                  {% else %}
                  <a style="text-decoration:none; color:black" href="/accounts/login/"><h5 class="card-title">{{single_course.title}}</h5></a>
                  {% endif %}
                  <h6>Instructor: <i>{{single_course.instructor.name}}</i></h6>
                  <p class="card-text">
                    {{single_course.semi_des}}
                  </p>
                  <div class="course-info">
                    <div class="float-start">
                      <span style="color: #7783ac"
                        ><i class="fa-solid fa-users"></i> {{single_course.usercourse_set.all.count}} students</span
                      ><br />
                      <span style="color: #7783ac"
                        ><i class="fa-solid fa-book"></i> {{single_course.video_set.all.count}} lessons</span
                      >
                    </div>

                    <div class="float-end">
                      {% if single_course.price == 0 %}
                        <h6 style="color: rgb(1, 130, 10); font-weight: 900">
                          <span class="badge bg-success" style="font-size: 18px">Free</span>
                        </h6>
                      {% else %}
                        <del style="color: red; font-weight: 900">৳ {{single_course.price}}</del>
                        <h6 style="color: rgb(1, 130, 10); font-weight: 900">
                          ৳ {% discount_calculation single_course.price single_course.discount %}
                        </h6>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <div class="row justify-content-center mb-5">
          <div class="featured-courses-btn text-center">
            <a href="{% url 'courses' %}" class="btn">Explore All Courses ></a>
          </div>
        </div>
      </div>
    </section>
    <!-- featured-courses  -->

    <!-- services -->
    <section class="services mb-4">
      <div class="container">
        <div class="row">
          <h4 style="font-weight: 900" class="text-center mt-2 mb-3">
            ----- WHAT SETS IUBAT ONLINE APART? -----
          </h4>
          <span style="font-size: 20px" class="text-center mt-4 mb-5"
            >Our flexible, online programs are designed to bring the IUBAT
            classroom to you, and are built around three key characteristics:
          </span>
        </div>
        <div class="row">
          <div class="col-md-4">
            <div class="services-container text-center">
              <img class="img-fluid" src="{% static 'assets/images/icons_gear_96x96.svg' %}" alt="" />
              <h5 class="services-title">Active</h5>
              <p>
                IUBAT Online courses are nothing like a typical
                sit-back-and-listen lecture. You’ll engage in a new activity
                every three to five minutes. Each element is designed to keep
                you interested, involved, and on your toes.
              </p>
            </div>
          </div>
          <div class="col-md-4">
            <div class="services-container text-center">
              <img
                class="img-fluid"
                src="{% static 'assets/images/icons_social_96x96.svg' %}"
                alt=""
              />
              <h5 class="services-title">Social</h5>
              <p>
                Engaging with your peers is a big part of what makes IUBAT
                Online unique. You exchange ideas, offer input, and seek out
                viewpoints from a community of learners gathered from around the
                globe. In the process, you learn from each other’s experiences
                and perspectives.
              </p>
            </div>
          </div>
          <div class="col-md-4">
            <div class="services-container text-center">
              <img
                class="img-fluid"
                src="{% static 'assets/images/icons_briefcase_96x96.svg' %}"
                alt=""
              />
              <h5 class="services-title">Case-Based</h5>
              <p>
                Immerse yourself in real-world learning. Lessons are brought to
                life through cases, which put you in the shoes of business
                leaders. Hear firsthand the challenges they faced, and wrestle
                with the same issues and imperfect information.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- services -->

    <!-- faq  -->
    <section class="faq">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-8">
            <h3 class="mt-5 mb-4" style="font-weight: 900">Top FAQs</h3>
            <hr style="color: white" />
            <h5
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#collapseExample"
              aria-expanded="false"
              aria-controls="collapseExample"
            >
              How are IUBAT Online courses delivered?
            </h5>
            <div class="collapse" id="collapseExample">
              <div class="card card-body faq-body">
                Our platform features short, highly produced videos of IUBAT
                faculty and guest experts, interactive graphs and exercises,
                cold calls to keep you engaged, and opportunities to contribute
                to a vibrant online community.
              </div>
            </div>
            <hr />
            <h5
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#collapseExample2"
              aria-expanded="false"
              aria-controls="collapseExample2"
            >
              Do I need to come to campus to participate in IUBAT Online
              programs?
            </h5>
            <div class="collapse" id="collapseExample2">
              <div class="card card-body faq-body">
                No, all of our programs are 100 percent online, and available to
                participants regardless of their location.
              </div>
            </div>
            <hr />
            <h5
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#collapseExample3"
              aria-expanded="false"
              aria-controls="collapseExample3"
            >
              Does IUBAT offer an online MBA?
            </h5>
            <div class="collapse" id="collapseExample3">
              <div class="card card-body faq-body">
                No, IUBAT doesn't offer an online MBA.
              </div>
            </div>
            <hr class="mb-5" />
          </div>
        </div>
      </div>
    </section>
    <!-- faq  -->
{% endblock %}